FROM ubuntu:22.04

COPY ../../backend /home/user/main

CMD cd /home/user/main && ls

# RUN apt update
# RUN apt install nodejs

# RUN cd /home/user/main/backend/build/src
# RUN npm install

# CMD cd /home/user/main/backend/build/src && node main.js